version: '3'
services:
  redis:
    image: redis:alpine
  demo:
    build: .
    ports:
      - "3000:3000"
    environment:
      DEMO_APP_ADDR: 0.0.0.0:3000
      DEMO_REDIS_ADDR: redis:6379
    depends_on:
      - redis